export const columns = [
    {
      name: "Organisation",
      selector: "scholarshipOrg",
      sortable: true,
    },
    {
      name: "Name of Scholarship",
      selector: "scholarshipName",
      sortable: true,
    },
    {
      name: "Scholarship Description",
      selector: "scholarshipDesc",
      sortable: true,
    },
    {
      name: "File Owner",
      selector: "fileOwner",
      sortable: true,
    },
    {
      name: "File Description",
      selector: "fileDesc",
      sortable: true,
    },
    // {
    //   name: "File Size",
    //   selector: "fileSize",
    //   sortable: true,
    // },
    // {
    //   name: "Last Modified",
    //   selector: "lastMod",
    //   sortable: true,
    // },
  ];
  export const loldata = [
    {
      fileNumber: 1,
      type:"file",
      path:[],
      fileName: "Prats.jpeg",
      docType: "Ration Card",
      fileType:"image/jpeg",
      fileOwner:"Prats",
      fileDesc: "This is a ration card",
    },
    {
      fileNumber: 2,
      type:"file",
      path:[],
      fileName: "DhruvAadhar.pdf",
      docType: "Aadhar Card",
      fileType:"application/pdf",
      fileOwner:"Dhruv Kud",
      fileDesc: "Fake Aadhar card for clubbing",
    },
    {
      fileNumber: 3,
      type:"file",
      path:[],
      fileName: "BhavyaAadhar.pdf",
      docType: "Aadhar Card",
      fileType:"application/pdf",
      fileOwner:"Bhavya Gor",
      fileDesc: "Fake Card",
    },
    {
      fileNumber: 4,
      type:"file",
      path:[],
      fileName: "license.pdf",
      docType: "Driving License",
      fileType:"application/pdf",
      fileOwner:"Bhavya Gor",
      fileDesc: "Fake Card",
    },
    {
      fileNumber: 5,
      type:"file",
      path:[],
      fileName: "RuchiPassport.pdf",
      docType: "Passport",
      fileType:"application/pdf",
      fileOwner:"Ruchi",
      fileDesc: "Fake Card",
    },
    {
      fileNumber: 6,
      type:"file",
      path:[],
      fileName: "BhavyaPan.pdf",
      docType: "PAN Card",
      fileType:"image/jpeg",
      fileOwner:"Prats",
      fileDesc: "Fake Card",
    },
    {
      fileNumber: 7,
      type:"file",
      path:[],
      fileName: "pan.pdf",
      docType: "PAN Card",
      fileType:"image/jpeg",
      fileOwner:"Prath",
      fileDesc: "Fake Card",
    },
    {
      fileNumber: 8,
      type:"file",
      path:[],
      fileName: "Bhavya.pdf",
      docType: "Driving License",
      fileType:"application/pdf",
      fileOwner:"Bhavya Gor",
      fileDesc: "Fake Card",
    },
    {
      fileNumber: 9,
      type:"file",
      path:['f1'],
      fileName: "rux.pdf",
      docType: "Driving License",
      fileType:"application/pdf",
      fileOwner:"ruxgav",
      fileDesc: "Drink Drive arrest",
    },
    {
      fileNumber: 10,
      type:"folder",
      path:[],
      fileName: "f1",
      docType: "Folder",
      fileType:"-",
      fileOwner:"ruxgav",
      fileDesc: "Mera Drive",
    },
  ];
  // const file = {
  //   fileName, //
  //   docType,//aadhar
  //   fileType,// pdf/
  //   fileOwner,
  //   fileDesc,
  //   hash,
  //   fileEmail,
  //   fileVisibility: true
  // };
  